apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ucnnct-mock
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api/v1/control-plane
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: 7300
          - path: /health
            pathType: Exact
            backend:
              service:
                name: orchestrator
                port:
                  number: 7300
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mock-control-center
                port:
                  number: 80
