apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ucnnct-mock
resources:
  - namespace.yaml
  - ./mock-control-center
  - ./orchestrator
  - ./worker-service
  - ./mock-user-service
  - ingress.yaml
