apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - image-updater-mock-control-center.yaml
  - image-updater-orchestrator.yaml
  - image-updater-worker-service.yaml
  - image-updater-mock-user-service.yaml
