apiVersion: v1
kind: Secret
metadata:
  name: mock-user-service-secrets
  labels:
    app.kubernetes.io/name: mock-user-service
    app.kubernetes.io/part-of: ucnnct-mock
type: Opaque
stringData:
  STAGING_IDENTITY_ADMIN_PASSWORD: "admin"
  STAGING_IDENTITY_CLIENT_SECRET: "MfkAe9Nk7tM1HhqWsCD4A5SuC9ItTDTH"
  STAGING_IDENTITY_DEFAULT_PASSWORD: "MockPass123!"
