apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/worker-service
images:
  - name: ghcr.io/ucnnct/mock-worker-service
    newTag: 0.11.0
    newName: ghcr.io/ucnnct/mock-worker-service
