apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/part-of: ucnnct-mock
spec:
  selector:
    app.kubernetes.io/name: orchestrator
  ports:
    - name: http
      port: 7300
      targetPort: http
