apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mock-rollout-platform-application.yaml
  - ./mock-image-updater-staging-application.yaml
  - ./mock-staging-application.yaml
