apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ucnnct-mock-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/ucnnct/ucnnct-mock-gitops.git
    targetRevision: main
    path: apps/overlay/staging
  destination:
    server: https://172.31.253.146:6443
    namespace: ucnnct-mock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
